# SPDX-FileCopyrightText: : 2021 Tom Brown
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-server
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - pypsa=0.17.1
  - snakemake-minimal
  - yaml
  - numpy<=1.19 # until new PyPSA after 27-06-21
  - pandas<1.3
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - pyomo
  - matplotlib
  - flask
  - redis
  - redis-py
  - rq
  - geopandas
  - pip:
      - vresutils==0.3.1
