# SPDX-FileCopyrightText: : 2022 Tom Brown
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-server
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - pypsa>=0.18
  - snakemake-minimal
  - yaml
  - numpy
  - pandas
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - pyomo
  - matplotlib
  - flask
  - redis
  - redis-py
  - rq
  - geopandas
  - pip:
      - vresutils==0.3.1
